experiment: "eval_deepgaze_iie_pretrained"
output_dir: "outputs/eval/deepgaze_iie_pretrained"
prediction_cache_dir: "predictions"
cache_predictions: true
predict_only: false

models:
  - "deepgaze_iie"

active_models:
  - "deepgaze_iie"

model_kwargs:
  deepgaze_iie:
    use_uniform_centerbias: true
    pretrained: true

datasets:
  - name: "folder"
    root: "data/img_bin"
    split: "test"
    include_list: "splits/test.txt"
